gem 'bundler',               '0.8.1'
gem 'rack',                  '1.1.0'
gem 'sinatra',               '0.9.4'
gem 'json'
gem 'dm-core',               '0.10.2'
gem 'dm-aggregates',         '0.10.2'
gem 'dm-timestamps',         '0.10.2'
gem 'dm-validations',        '0.10.2'
gem 'data_objects',          '0.10.1'
gem 'do_mysql',              '0.10.1'
gem 'extlib',                '0.9.14'
gem 'addressable',           '2.1.1'
disable_system_gems